//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutopesulaTellimused.WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutopesulaTellimused.WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kas soovid valitud tellimuse kustutada?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selle reg-numbriga tellimus on juba olemas!.
        /// </summary>
        internal static string ErrDuplicatePlate {
            get {
                return ResourceManager.GetString("ErrDuplicatePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg-number peab olema 2–10 märgiga!.
        /// </summary>
        internal static string ErrInvalidPlate {
            get {
                return ResourceManager.GetString("ErrInvalidPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali tabelist tellimus, mida kustutada!.
        /// </summary>
        internal static string ErrSelectOrderToDelete {
            get {
                return ResourceManager.GetString("ErrSelectOrderToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vali tabelist tellimus, mida muuta!.
        /// </summary>
        internal static string ErrSelectOrderToEdit {
            get {
                return ResourceManager.GetString("ErrSelectOrderToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali pesuprogramm!.
        /// </summary>
        internal static string ErrSelectProgram {
            get {
                return ResourceManager.GetString("ErrSelectProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali sõiduki liik!.
        /// </summary>
        internal static string ErrSelectVehicle {
            get {
                return ResourceManager.GetString("ErrSelectVehicle", resourceCulture);
            }
        }
    }
}
